### ISSUE TITLE
Planungszonen kommen auch im Thema "Nutzungsplanung überlagernd".  

### ISSUE THREAD

**Issue by Luescher** [sogis-oereb/oereb-gretljobs#24]
### Beschreibung

Planungszonen im Thema "Nutzungsplanung überlagernd" entfernen auch im WMS resp. Legende

Bsp. Testumgebung CH133288063749

### Urgentticket

- [ ] Der Fehler verunmöglicht das weitere Arbeiten und muss schnellstmöglicht gefixed werden.

**Comment by edigonzales** [comment]
fixed https://github.com/sogis-oereb/oereb-gretljobs/commit/00c5805a785fc942d3376d11b46edcee21a600c5

**Comment by edigonzales** [comment]
done https://github.com/sogis-oereb/oereb-wms/commit/521e14254a6e5bebd394b4beb12d062d1f862fcb
