### ISSUE TITLE
Bei Baulinien "Kanton" kommen keine Rechtsvorschriften 

### ISSUE THREAD

**Issue by Luescher** [sogis-oereb/oereb-gretljobs#25]
### Beschreibung

Siehe CH293274010689 oder CH228957320650
So wie ich sehe sind die Rechtsvorschriften im Schema  arp_nutzungsplanung_kanton_oerebv2 noch vorhanden, aber in der ÖREB-DB nicht mehr.

### Urgentticket

- [ ] Der Fehler verunmöglicht das weitere Arbeiten und muss schnellstmöglicht gefixed werden.

**Comment by Luescher** [comment]
[kanton.zip](https://github.com/sogis-oereb/oereb-gretljobs/files/8488682/kanton.zip)

**Comment by edigonzales** [comment]
Siehe auch Rickenbach 398 / CH851532800633. Es fehlen die Baulinien im WMS und in der ÖREB-DB. Kantonale Baulinien sind aber vorhanden.

**Comment by edigonzales** [comment]
fixed https://github.com/sogis-oereb/oereb-gretljobs/commit/715f92b9b8269c1104562b3a3a2d58d5619fa1c8 

Siehe "ch.so.arp.oereb_nutzungsplanung_kantonal": das war falsch.
