### ISSUE TITLE
Titel Rechtsvorschrift anders als in Version 1.0

### ISSUE THREAD

**Issue by Luescher** [sogis-oereb/oereb-gretljobs#26]
### Beschreibung

Ich glaube es wäre besser wenn man den Titel bei den RRB's zusammensetzt aus Titel und offiziellerTitel .
z.B. bei CH893281620627 
neu:"Rickenbach: Gesamtrevision der Ortsplanung"
alt: "Regierungsratsbeschluss, 2019/1235" 

Verbesserungsvorschlag (Titel und offiziellerTitel): "Regierungsratsbeschluss, Rickenbach: Gesamtrevision der Ortsplanung"

Bei den anderen Arten z.B.  Zonenreglement kommt es auch anders aber i.O. resp. finde ich besser.
neu: "Zonenreglement der Einwohnergemeinde 4613 Rickenbach SO"
alt: "Zonenreglement, 093-ZR:"

### Urgentticket

- [ ] Der Fehler verunmöglicht das weitere Arbeiten und muss schnellstmöglicht gefixed werden.

**Comment by edigonzales** [comment]
Habe es bei Nutzungsplanung kommunal und kantonal, Planungszonen und Gewässerraum gemacht. Ist es anderswo auch noch sinnvoll?

**Comment by edigonzales** [comment]
https://github.com/sogis-oereb/oereb-gretljobs/commit/66b35c0d1f90b41363b327a089f8163e21e34193

**Comment by Luescher** [comment]
Einzelschutz ADA, Geotop und Naturreservate

**Comment by edigonzales** [comment]
@Luescher 
ADA: Gemacht. Aber nur wenn ich beim Datenumbau den Titel korrigiere. D.h. Linebreaks rauslösche, sonst validiert es nicht mehr.
Geotop: Würde ich glaub nicht machen. Da gibt es dann Titel wie "RRB Pfingsthöhle", "RRB_HuppergrubeRickenbach.pdf". Schludrig wie so viele.
Naturreservate: Gemacht. Konnte es aber irgendwie nicht verifizieren, weil ich kein Gebiet gefunden habe, wo das greifen würde.
