### ISSUE TITLE
Falls kantonale und kommunale Baulinien betroffen sind kommt bei der zuständigen Stelle nur eine Stelle

### ISSUE THREAD

**Issue by Luescher** [sogis-oereb/oereb-gretljobs#27]
### Beschreibung

Bsp. CH170673583223, CH367432064471
![eine_stelle](https://user-images.githubusercontent.com/3929984/164036730-1102c61d-f9af-4f15-bd48-f9779d08a11a.jpg)

### Urgentticket

- [ ] Der Fehler verunmöglicht das weitere Arbeiten und muss schnellstmöglicht gefixed werden.

**Comment by edigonzales** [comment]
Fixed im Web GIS Client.
