### ISSUE TITLE
Waldreservate mit Rechtstatus != "inKraft" nicht publizieren im ÖREB-Kataster

### ISSUE THREAD

**Issue by Luescher** [sogis-oereb/oereb-gretljobs#30]
### Beschreibung

Momentan werden auch Änderungen publiziert mit dem GRETL-Job "oerebv2_waldreservate"

### Urgentticket

- [ ] Der Fehler verunmöglicht das weitere Arbeiten und muss schnellstmöglicht gefixed werden.

**Comment by schmandr** [comment]
Ich schliesse das Ticket, weil dieses Repo archiviert wird. Falls nötig das Ticket in https://github.com/sogis/oereb-gretljobs neu erstellen.
